import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Bot,
  Brain,
  Camera,
  Code2,
  Compass,
  GitBranch,
  HeartHandshake,
  LayoutGrid,
  Mail,
  MapPin,
  Megaphone,
  MousePointerClick,
  Newspaper,
  Palette,
  PenTool,
  Repeat,
  Search,
  Share2,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  Target,
  TrendingUp,
  Users,
  Video,
  Workflow,
  Zap,
} from "lucide-react";

/** Icoon per dienstlink. Consistente visuele scan in het mega-menu */
const byHref: Record<string, LucideIcon> = {
  "/diensten/strategie": Compass,
  "/diensten/cro": MousePointerClick,
  "/diensten/leadgeneratie": Users,
  "/diensten/tracking": BarChart3,
  "/diensten/shopify-enterprise": ShoppingBag,
  "/diensten/webdevelopment": Code2,
  "/diensten/web-apps": LayoutGrid,
  "/diensten/optimalisatie": Zap,
  "/diensten/webdesign": PenTool,
  "/diensten/branding": Palette,
  "/diensten/animaties": Sparkles,
  "/diensten/seo": Search,
  "/diensten/ai-zoek": Brain,
  "/diensten/local-seo": MapPin,
  "/diensten/content-marketing": Newspaper,
  "/diensten/reviews": Star,
  "/diensten/google-ads": Target,
  "/diensten/meta-ads": Megaphone,
  "/diensten/adverteren": TrendingUp,
  "/diensten/social-media": Share2,
  "/diensten/ugc": Camera,
  "/diensten/influencer-marketing": HeartHandshake,
  "/diensten/marketplaces": Store,
  "/diensten/media": Video,
  "/diensten/email": Mail,
  "/diensten/retentie": Repeat,
  "/diensten/automatisering": Workflow,
  "/diensten/workflows": GitBranch,
  "/diensten/chatbots": Bot,
};

export function megaMenuIconForHref(href: string): LucideIcon {
  return byHref[href] ?? LayoutGrid;
}
