import type { SeoLandingStep } from "@/data/seo-landings/types";

/** Unieke proces-stappen per national batch 2 en 3 slug. */
export const BATCH2_BATCH3_PROCESS: Partial<
  Record<string, readonly SeoLandingStep[]>
> = {
  "conversie-optimalisatie": [
    { title: "Funnel meten", body: "GA4, Clarity of shop-data. Waar haken bezoekers af?" },
    { title: "Hypothese op impact", body: "Checkout, formulier, trust, snelheid. Grootste lek eerst." },
    { title: "Fix live zetten", body: "Ik pas pagina's zelf aan. Direct, zonder ticket naar een derde team." },
    { title: "Opnieuw meten", body: "Conversie vóór en na. Opschalen als het verschil zichtbaar is." },
  ],
  "lokale-seo": [
    { title: "GBP-audit", body: "Profiel, categorie, reviews, posts. Wat mist Google?" },
    { title: "Site + NAP", body: "Landings op lokale intentie, schema, snelheid op mobiel." },
    { title: "Reviews & citaties", body: "Ritme voor vragen, consistentie over kanalen." },
    { title: "Maps + organisch", body: "Lokaal ranken en ads op dezelfde boodschap." },
  ],
  "zoekmachine-optimalisatie": [
    { title: "Keyword & marge", body: "Koopintentie, niet alleen volume. Prioriteiten op omzet." },
    { title: "Techniek & structuur", body: "Crawl, snelheid, interne links, silo's." },
    { title: "Landings bouwen", body: "Antwoord-pagina's schrijven én publiceren." },
    { title: "Posities + pipeline", body: "Rankings meten én wat ze opleveren in leads." },
  ],
  "technische-seo": [
    { title: "Crawl & index", body: "Wat ziet Google, wat wordt geblokkeerd?" },
    { title: "Snelheid & CWV", body: "Mobiel eerst. LCP, INP, CLS op echte pagina's." },
    { title: "Fix in code", body: "Canonicals, schema, redirects. Ik voer uit, geen PDF." },
    { title: "Monitoring", body: "Search Console, alerts. Blijven indexeerbaar na updates." },
  ],
  "ppc-bureau": [
    { title: "Account & intentie", body: "Search, Shopping, remarketing. Wat past bij marge?" },
    { title: "Structuur op ROAS", body: "Campagnes per koopmoment, geen alles-in-één-mand." },
    { title: "Landings + tracking", body: "Message match, GA4, conversies vóór opschalen." },
    { title: "Wekelijks bijsturen", body: "Zoektermen, budget, creatives. Actie, geen dashboard." },
  ],
  "e-commerce-marketing": [
    { title: "Shop-diagnose", body: "SKU's, marge, cart, mail. Waar lekt omzet?" },
    { title: "Kanaal-volgorde", body: "Feed, SEO, Shopping, Meta, retentie. Eerlijk prioriteren." },
    { title: "Uitrollen gekoppeld", body: "Zelfde productdata in shop, feed en campagnes." },
    { title: "Unit economics", body: "CAC, AOV, LTV. Opschalen als rekensom klopt." },
  ],
  "e-mailmarketing": [
    { title: "Lijst & consent", body: "Segmenten, shop-koppeling, privacy klopt." },
    { title: "Flows prioriteren", body: "Welkom, abandon, post-purchase. Wat eerst geld oplevert." },
    { title: "Copy & test", body: "Subject, timing, offer. Jij keurt, ik bouw." },
    { title: "Omzet per flow", body: "Euro's per mailreeks, niet alleen open rate." },
  ],
  "tiktok-ads-bureau": [
    { title: "Fit-check", body: "Past TikTok bij product, marge en site op mobiel?" },
    { title: "Creative-test", body: "9:16 hooks, UGC, korte loops. Eén variabele tegelijk." },
    { title: "Landings mobiel", body: "Snelheid, CTA, checkout. Ad en pagina matchen." },
    { title: "ROAS meten", body: "Views zijn vanity. Checkout telt." },
  ],
  "leadgeneratie-website": [
    { title: "Doel per pagina", body: "Wie moet bellen, formulier of demo? Eén job per URL." },
    { title: "Landings + ads", body: "Message match met Google Ads en Meta Ads." },
    { title: "Formulier & trust", body: "Kort, duidelijk, social proof bij CTA." },
    { title: "Kwaliteit meten", body: "Niet alleen volume. Welke bron levert sales?" },
  ],
  "woocommerce-naar-shopify": [
    { title: "URL-mapping", body: "Elke pagina: behouden, redirect of stop. SEO beschermen." },
    { title: "Data & feed", body: "Producten, varianten, prijzen, voorraad kloppen." },
    { title: "Theme & checkout", body: "Custom waar nodig. Test op mobiel en 4G." },
    { title: "Post-launch", body: "Tracking, mail, Shopping opnieuw valideren." },
  ],
  "google-ads-specialist": [
    { title: "Account-audit", body: "Zoektermen, structuur, conversies, landings." },
    { title: "Opschonen", body: "Leaks dicht, negatieven bij, budget herverdelen." },
    { title: "Landings fixen", body: "Message match. Ik pas pagina's zelf aan." },
    { title: "Wekelijks ritme", body: "Rapport met besluiten, niet alleen cijfers." },
  ],
  "google-ads-uitbesteden": [
    { title: "Toegang & baseline", body: "Ads, analytics, site. Weten waar je staat." },
    { title: "Structuur + tracking", body: "Conversies kloppen vóór budget omhoog." },
    { title: "Beheer live", body: "Zoektermen, biedingen, creatives, landings." },
    { title: "Maandelijks review", body: "ROAS, CPA, volgende prioriteit. Eerlijk advies." },
  ],
  "remarketing-google-ads": [
    { title: "Segmenten", body: "Cart, product, pricing. Niet iedereen die favicon zag." },
    { title: "Frequency & creative", body: "Caps, variatie, geen stalker-vibe." },
    { title: "Landings vervolg", body: "Pagina's die beslissen helpen, niet schreeuwen." },
    { title: "Koppeling mail", body: "Remarketing + flows waar het versterkt." },
  ],
  "facebook-ads-bureau": [
    { title: "Pixel & CAPI", body: "Signalen kloppen vóór campagnes draaien." },
    { title: "Doel + funnel", body: "Conversies, leads of catalog. Budget volgt doel." },
    { title: "Creative rotatie", body: "UGC, hooks, fatigue voorkomen." },
    { title: "ROAS op checkout", body: "Meta + landings in één hand." },
  ],
  "instagram-ads-bureau": [
    { title: "9:16 first", body: "Reels, Stories, mobiele landings." },
    { title: "Doelgroep test", body: "Interesses, lookalikes, retargeting." },
    { title: "Landings snel", body: "CTA boven fold, trust zichtbaar." },
    { title: "Meten op omzet", body: "Niet op likes. Checkout en leads." },
  ],
  "shopify-webshop-laten-maken": [
    { title: "Scope & groei", body: "Assortiment, B2B, feed, checkout." },
    { title: "Custom theme", body: "Waar theme store stopt: portalen, prijslijsten." },
    { title: "SEO bij launch", body: "Schema, collecties, snelheid groen." },
    { title: "Marketing-klaar", body: "Tracking, mail, campagnes als fundament staat." },
  ],
  "shopify-seo": [
    { title: "SKU-prioriteit", body: "Hero-producten eerst. Dunne pagina's later." },
    { title: "Techniek shop", body: "Filters, tags, duplicate content aanpakken." },
    { title: "Copy op intentie", body: "Titels, collecties, blog op echte vragen." },
    { title: "Rankings + feed", body: "Organisch en Shopping delen productdata." },
  ],
  "nextjs-website-laten-maken": [
    { title: "Architectuur", body: "Routes, CMS, forms, tracking. Stack op groei." },
    { title: "Design + copy", body: "Structuur vóór pixels. Conversie ingebouwd." },
    { title: "Build & CWV", body: "Server components, schema, Lighthouse groen." },
    { title: "Launch + SEO", body: "Indexeren, landings, klaar voor ads." },
  ],
  "website-laten-bouwen": [
    { title: "Doel scherp", body: "Wie moet wat doen? Niet eerst kleuren." },
    { title: "Sitemap & wireframe", body: "Pagina's per intentie, geen filler." },
    { title: "From scratch bouwen", body: "Next.js of Shopify custom. Custom code, geen page builder." },
    { title: "Live + meten", body: "Tracking, eerste optimalisaties op data." },
  ],
  "seo-audit": [
    { title: "Baseline scan", body: "Techniek, content, autoriteit, concurrentie." },
    { title: "Prioriteiten", body: "Impact × inspanning. Ranked lijst, geen roman." },
    { title: "Quick wins", body: "Wat deze week live kan." },
    { title: "Roadmap", body: "Volgorde voor komende maanden. Uitvoering optioneel bij mij." },
  ],
  "seo-uitbesteden": [
    { title: "Inventarisatie", body: "Rankings, techniek, content gaps." },
    { title: "Roadmap op marge", body: "Welke pagina's eerst, welke fixes nu." },
    { title: "Uitvoering", body: "Ik bouw en publiceer. Direct live, zonder wachten op derden." },
    { title: "Rapport + actie", body: "Posities én omzet per pagina waar mogelijk." },
  ],
  "linkbuilding-bureau": [
    { title: "Linkwaardige assets", body: "Gidsen, data, tools, cases. Echte waarde, geen gekochte spam." },
    { title: "Outreach waar zinvol", body: "Relevante sites, echte waarde." },
    { title: "Content die trekt", body: "Pagina's waar anderen naartoe willen linken." },
    { title: "Referral + rankings", body: "Traffic en posities, niet alleen DR." },
  ],
  "online-marketing-manager": [
    { title: "Kanalen in kaart", body: "Site, SEO, ads, mail. Wat lekt, wat wint?" },
    { title: "Volgorde kwartaal", body: "Eerlijk: soms SEO, soms CRO, soms Shopping." },
    { title: "Uitvoeren zelf", body: "Regie én hands-on. Eén senior, geen vijf juniors." },
    { title: "Wekelijkse regie", body: "Wat live, wat oplevert, wat volgende week." },
  ],
  "performance-marketing-bureau": [
    { title: "Attributie simpel", body: "Eén waarheid over leads en omzet." },
    { title: "Channel-mix", body: "Google Ads, Meta Ads, mail. Budget op ROAS." },
    { title: "Landings optimaliseren", body: "Waar budget naartoe stroomt, fix ik." },
    { title: "Opschalen op breakeven", body: "Rekensom eerst. Dan pas opschalen." },
  ],
  "cro-bureau": [
    { title: "Data + sessies", body: "Funnels, heatmaps, device splits." },
    { title: "Hypothese", body: "Checkout, formulier, trust, snelheid." },
    { title: "Implementeren", body: "Zelf in code. Zelfde week live." },
    { title: "Itereren", body: "Winnaar vasthouden, verliezer killen." },
  ],
  "tracking-google-analytics": [
    { title: "Event-map", body: "Purchases, leads, micro-conversies. Wat moet je meten?" },
    { title: "GTM + GA4", body: "Tags, triggers, consent mode. Test live." },
    { title: "Shop of site koppelen", body: "Enhanced ecommerce, B2B events." },
    { title: "Validatie", body: "Tag Assistant, echte orders. Waarheid vóór ads." },
  ],
};

export const BATCH2_BATCH3_PROCESS_TITLES: Partial<Record<string, string>> = {
  "conversie-optimalisatie": "CRO op echte data",
  "lokale-seo": "Lokaal ranken in Maps",
  "zoekmachine-optimalisatie": "SEO op koopintentie",
  "technische-seo": "Techniek eerst, rankings daarna",
  "ppc-bureau": "PPC met marge in vizier",
  "e-commerce-marketing": "Shop als systeem",
  "e-mailmarketing": "Mail op omzet per flow",
  "tiktok-ads-bureau": "TikTok met checkout-doel",
  "leadgeneratie-website": "Leads die sales voeden",
  "woocommerce-naar-shopify": "Migratie zonder dip",
  "google-ads-specialist": "Specialist + landings",
  "google-ads-uitbesteden": "Uitbesteden met actie",
  "remarketing-google-ads": "Warm verkeer terug",
  "facebook-ads-bureau": "Meta campagnes + landings",
  "instagram-ads-bureau": "Instagram op mobiel",
  "shopify-webshop-laten-maken": "Shopify custom traject",
  "shopify-seo": "Shopify SEO end-to-end",
  "nextjs-website-laten-maken": "Next.js from scratch",
  "website-laten-bouwen": "Bouwen met marketing erin",
  "seo-audit": "Audit met prioriteiten",
  "seo-uitbesteden": "SEO met uitvoering",
  "linkbuilding-bureau": "Links via waarde",
  "online-marketing-manager": "Regie onder één dak",
  "performance-marketing-bureau": "Performance op omzet",
  "cro-bureau": "Meer uit bestaand verkeer",
  "tracking-google-analytics": "Meten vóór optimaliseren",
};
